/* eslint-disable */
/**
 * 本文件由 `cargo run -p ci-core --bin export-bindings` 生成，请勿手改。
 *
 * 来源：crates/ci-domain（specta 派生）。前端只允许用这里的类型，
 * 这样「Rust 改了字段、前端还按老结构读」这类漂移会在 CI 就被拦住。
 */
// This file has been generated by Specta. Do not edit this file manually.
/**  能力评价结果 */
export type Ability = {
	axes: Axis[],
	/**  综合分（掌握度 × 覆盖系数） */
	overall: number,
	/**  掌握度（只在有作答的题型上加权） */
	mastery: number,
	/**  均衡度：答过 <2 个题型时为 None（与 JS 的 null 对应） */
	balance: number | null,
	coverage: number,
	attempts: number,
	filled: number,
	max_rate: number,
	min_rate: number,
	/**  最弱/最强轴的**下标**（axes 内），无作答时为 None */
	weakest: number | null,
	strongest: number | null,
	grade: Grade,
	comment: string,
};

/**  大屏/学生端的"能力画像"打包 */
export type AbilityPack = {
	id: string,
	name: string,
	kind: string,
	overall: number,
	coverage: number,
	balance: number | null,
	attempts: number,
	grade: GradePack,
	axes: AxisPack[],
	weakest: AxisBrief | null,
	strongest: AxisBrief | null,
	comment: string,
};

/**  雷达上的一条轴（rate 为整数百分比，供前端直接显示） */
export type Axis = {
	key: string,
	label: string,
	color: string,
	weight: number | null,
	attempts: number,
	correct: number,
	/**  掌握度（整数百分比） */
	rate: number,
	correct_rate: number | null,
};

export type AxisBrief = {
	label: string,
	rate: number,
};

export type AxisPack = {
	key: string,
	label: string,
	color: string,
	rate: number,
	attempts: number,
};

export type Buzz = {
	team_id: string,
	qid?: string | null,
	sid?: string | null,
	at: number,
};

/**  抢答结果 */
export type BuzzOutcome = {
	/**  同一队同一题重复抢答被忽略 */
	dup: boolean,
	team_name: string,
};

export type ClassStudent = {
	id: string,
	name: string,
	team_id?: string | null,
	active?: boolean,
};

export type ClassTeam = {
	id: string,
	name: string,
	color?: string,
	icon?: string,
	/**  全员 id（用于"队伍里没有成员"判断与取第一个成员） */
	member_ids?: string[],
};

/**  命令处理结果（对应 JS handleCmd 的返回值，外加要落库的副作用） */
export type CmdOutcome = 
/**  不认识的命令 */
{ kind: "ignored" } | 
/**  入座 */
{ kind: "hello"; team_id: string | null } | 
/**  抢答（dup=true 表示重复被忽略） */
{ kind: "buzz"; dup: boolean; team_id: string | null } | 
/**  提交失败：队伍没有成员 */
{ kind: "answerNoStudent"; team_id: string | null } | 
/**  重复提交，已忽略 */
{ kind: "answerDuplicate"; sid: string } | 
/**  主观题：进待确认队列 */
{ kind: "answerPending"; sid: string } | 
/**  客观题：自动判分并记分 */
{ kind: "answerScored"; sid: string; result: string; points: number | null };

/**  一次命令处理的完整产物 */
export type CmdResult = {
	outcome: CmdOutcome,
	/**  要写进实时流的条目（按顺序插入，新的在前） */
	feeds: FeedItem[],
	/**  主观题待确认条目 */
	pending: Pending | null,
	/**  抢答条目（若发生） */
	buzz: Buzz | null,
	/**  记分请求（客观题才有） */
	score: ScoreRequest | null,
};

/**  实时流条目（教师端右上角滚动显示） */
export type FeedItem = {
	kind: string,
	team_id?: string | null,
	sid?: string | null,
	qid?: string | null,
	result?: string | null,
	answer?: string | null,
	expected?: string | null,
	points?: number | null,
	text: string,
	at: number,
};

/**  评级档位 */
export type Grade = {
	key: string,
	short: string,
	label: string,
	color: string,
	tip: string,
};

export type GradePack = {
	key: string,
	short: string,
	label: string,
	color: string,
};

/**  待确认提交（主观题由老师判定） */
export type Pending = {
	sid: string,
	team_id?: string | null,
	qid?: string | null,
	quiz_id?: string | null,
	/**  提交内容可读化后的文本 */
	answer: string,
	backlog?: boolean,
	at: number,
};

export type Phase = "idle" | "rollcall" | "question" | "review";

/**  题目（判分需要的字段 + 计分需要的题型/自定义分值；其余字段仍在 dump 里，由前端展示） */
export type Question = {
	options?: string[],
	answer?: string,
	/**  题型 key（basic/advanced/extended/improve），计分要用 */
	tier?: string,
	/**  题目自定义分值；为 None 时取题型权重 */
	points?: number | null,
};

/**  环节相关的运行态（对应 state.runtime 里与课堂有关的部分） */
export type Runtime = {
	phase?: string,
	quiz_id?: string | null,
	qid?: string | null,
	accepting?: boolean,
	reveal?: boolean,
	/**  当前被点到的学生（点名环节大屏用） */
	sid?: string | null,
};

/**  记分请求（由存储层执行：写流水 + 落库） */
export type ScoreRequest = {
	sid: string,
	qid: string | null,
	tier: string,
	result: string,
	note: string,
	points: number | null,
};

/**  一条流水的算分快照（写库前的那部分） */
export type ScoreSnapshot = {
	sid: string,
	qid?: string | null,
	tier?: string,
	result?: string,
	base: number | null,
	ratio: number | null,
	points: number | null,
	source?: string,
};

/**  计分相关设置（只取算分要用的三项） */
export type ScoringSettings = {
	half_ratio?: number | null,
	fast_bonus?: number | null,
	wrong_penalty?: number | null,
};

/**  学生命令（对应 cmd.kind = hello | buzz | answer） */
export type StudentCmd = {
	kind: string,
	team_id?: string | null,
	sid?: string | null,
	qid?: string | null,
	choice?: string[],
	text?: string | null,
	skip?: boolean,
	backlog?: boolean,
};

export type TeamStat = {
	teamId: string,
	name: string,
	color: string,
	icon: string,
	correct: number,
	attempts: number,
	creditRate: number | null,
	score: number | null,
	memberCount: number,
};

/**  题型（权重是计分核心） */
export type Tier = {
	key: string,
	label: string,
	weight: number | null,
	color?: string,
	desc?: string,
};

/**  题型统计（finalizeBucket 之后的形态） */
export type TierStat = {
	key: string,
	label: string,
	color?: string,
	weight?: number | null,
	attempts: number,
	correct: number,
	/**  掌握度百分比（已按 halfRatio 折算，保留一位小数，与 JS 的 pct 一致） */
	credit_rate?: number | null,
	/**  正确率百分比 */
	correct_rate?: number | null,
};
