/* eslint-disable */
/**
 * 本文件由 `cargo run -p ci-core --bin export-bindings` 生成，请勿手改。
 *
 * 来源：crates/ci-domain（specta 派生）。前端只允许用这里的类型，
 * 这样「Rust 改了字段、前端还按老结构读」这类漂移会在 CI 就被拦住。
 */
// This file has been generated by Specta. Do not edit this file manually.
/**  能力评价结果 */
export type Ability = {
	axes: Axis[],
	/**  综合分（掌握度 × 覆盖系数） */
	overall: number,
	/**  掌握度（只在有作答的题型上加权） */
	mastery: number,
	/**  均衡度：答过 <2 个题型时为 None（与 JS 的 null 对应） */
	balance: number | null,
	coverage: number,
	attempts: number,
	filled: number,
	max_rate: number,
	min_rate: number,
	/**  最弱/最强轴的**下标**（axes 内），无作答时为 None */
	weakest: number | null,
	strongest: number | null,
	grade: Grade,
	comment: string,
};

/**  大屏/学生端的"能力画像"打包 */
export type AbilityPack = {
	id: string,
	name: string,
	kind: string,
	overall: number,
	coverage: number,
	balance: number | null,
	attempts: number,
	grade: GradePack,
	axes: AxisPack[],
	weakest: AxisBrief | null,
	strongest: AxisBrief | null,
	comment: string,
};

/**  雷达上的一条轴（rate 为整数百分比，供前端直接显示） */
export type Axis = {
	key: string,
	label: string,
	color: string,
	weight: number | null,
	attempts: number,
	correct: number,
	/**  掌握度（整数百分比） */
	rate: number,
	correct_rate: number | null,
};

export type AxisBrief = {
	label: string,
	rate: number,
};

export type AxisPack = {
	key: string,
	label: string,
	color: string,
	rate: number,
	attempts: number,
};

/**  题库里的完整题目 */
export type BankQuestion = {
	id: string,
	tier: string,
	/**  自定义分值；None 表示取题型权重 */
	points: number | null,
	stem: string,
	answer: string,
	options: string[],
	tags: string[],
	source: string,
	note: string,
	archived: boolean,
	createdAt: number,
};

export type Buzz = {
	teamId: string,
	qid?: string | null,
	sid?: string | null,
	at: number,
};

/**  抢答结果 */
export type BuzzOutcome = {
	/**  同一队同一题重复抢答被忽略 */
	dup: boolean,
	teamName: string,
};

export type ClassStudent = {
	id: string,
	name: string,
	teamId?: string | null,
	active?: boolean,
};

export type ClassTeam = {
	id: string,
	name: string,
	color?: string,
	icon?: string,
	/**  全员 id（用于"队伍里没有成员"判断与取第一个成员） */
	memberIds?: string[],
};

/**  课堂协同的即时状态（`state.classroom`，由 classroom.js 懒创建） */
export type ClassroomBox = {
	buzz: Buzz[],
	pending: Pending[],
	feed: FeedItem[],
};

/**  整份课堂状态（`CI.store.get()` 的返回形状） */
export type ClassroomState = {
	version: number,
	rev: number,
	updatedAt: number,
	settings: Settings,
	tiers: Tier[],
	tags: string[],
	teams: Team[],
	students: Student[],
	bank: BankQuestion[],
	quizzes: Quiz[],
	currentQuizId: string | null,
	rollcall: RollcallState,
	logs: LogItem[],
	/**  运行时上下文（本地记忆，不参与同步） */
	runtime: Runtime,
	classroom: ClassroomBox,
};

/**  命令处理结果（对应 JS handleCmd 的返回值，外加要落库的副作用） */
export type CmdOutcome = 
/**  不认识的命令 */
{ kind: "ignored" } | 
/**  入座 */
{ kind: "hello"; team_id: string | null } | 
/**  抢答（dup=true 表示重复被忽略） */
{ kind: "buzz"; dup: boolean; team_id: string | null } | 
/**  提交失败：队伍没有成员 */
{ kind: "answerNoStudent"; team_id: string | null } | 
/**  重复提交，已忽略 */
{ kind: "answerDuplicate"; sid: string } | 
/**  主观题：进待确认队列 */
{ kind: "answerPending"; sid: string } | 
/**  客观题：自动判分并记分 */
{ kind: "answerScored"; sid: string; result: string; points: number | null };

/**  一次命令处理的完整产物 */
export type CmdResult = {
	outcome: CmdOutcome,
	/**  要写进实时流的条目（按顺序插入，新的在前） */
	feeds: FeedItem[],
	/**  主观题待确认条目 */
	pending: Pending | null,
	/**  抢答条目（若发生） */
	buzz: Buzz | null,
	/**  记分请求（客观题才有） */
	score: ScoreRequest | null,
};

/**  实时流条目（教师端右上角滚动显示） */
export type FeedItem = {
	kind: string,
	teamId?: string | null,
	sid?: string | null,
	qid?: string | null,
	result?: string | null,
	answer?: string | null,
	expected?: string | null,
	points?: number | null,
	text: string,
	at: number,
};

/**  评级档位 */
export type Grade = {
	key: string,
	short: string,
	label: string,
	color: string,
	tip: string,
};

export type GradePack = {
	key: string,
	short: string,
	label: string,
	color: string,
};

/**  审计日志 */
export type LogItem = {
	id: string,
	/**  日志类型（"添加学生"/"课堂环节"/"抢答"…） */
	type?: string,
	detail: string,
	at: number,
};

/**  待确认提交（主观题由老师判定） */
export type Pending = {
	sid: string,
	teamId?: string | null,
	qid?: string | null,
	quizId?: string | null,
	/**  提交内容可读化后的文本 */
	answer: string,
	backlog?: boolean,
	at: number,
};

export type Phase = "idle" | "rollcall" | "question" | "review";

/**  题目（判分需要的字段 + 计分需要的题型/自定义分值；其余字段仍在 dump 里，由前端展示） */
export type Question = {
	options?: string[],
	answer?: string,
	/**  题型 key（basic/advanced/extended/improve），计分要用 */
	tier?: string,
	/**  题目自定义分值；为 None 时取题型权重 */
	points?: number | null,
};

/**  试卷 */
export type Quiz = {
	id: string,
	name: string,
	note: string,
	createdAt: number,
	/**  0 表示未关闭 */
	closedAt: number,
	questionIds: string[],
	/**  本套题的流水（与全局 records 是同一批数据的两处索引） */
	records: ScoreRecord[],
};

/**  一次点名记录 */
export type RollHistoryEntry = {
	id: string,
	sid: string,
	at: number,
	quizId: string | null,
	qid: string | null,
};

/**  点名设置与轮次池（`state.rollcall`） */
export type RollcallState = {
	/**  even=轮次池均匀 / random=纯随机 / least=最少被点优先 */
	mode: string,
	/**  'all' 或队伍 id */
	scope: string,
	excludeAnswered: boolean,
	recentExclude: number,
	history: RollHistoryEntry[],
	/**  本轮尚未被点到的学生 id */
	roundPool: string[],
	round: number,
};

/**  环节相关的运行态（对应 state.runtime 里与课堂有关的部分） */
export type Runtime = {
	phase?: string,
	quizId?: string | null,
	qid?: string | null,
	accepting?: boolean,
	reveal?: boolean,
	/**  当前被点到的学生（点名环节大屏用） */
	sid?: string | null,
};

/**  一条积分流水（与 `store.js` 的 `normalizeRecord` 字段一致） */
export type ScoreRecord = {
	id: string,
	sid: string | null,
	qid: string | null,
	/**  计分时的题型快照（题干/权重改动不影响历史） */
	tier: string,
	quizId: string | null,
	result: string,
	/**  该题基准分 */
	base: number,
	ratio: number,
	/**  实际记入积分（可为负） */
	points: number,
	source: string,
	note: string,
	at: number,
	/**  操作来源页签，便于排查 */
	by: string,
};

/**  记分请求（由存储层执行：写流水 + 落库） */
export type ScoreRequest = {
	sid: string,
	qid: string | null,
	tier: string,
	result: string,
	note: string,
	points: number | null,
	/**
	 *  抢答名次（1 起）：本队此前是否对该题抢过答、排第几。
	 *  答对且有名次 → 存储层按名次加分（第 1 个 +2 / 第 2 个 +1，见 ScoringSettings）。
	 */
	rank?: number | null,
};

/**  一条流水的算分快照（写库前的那部分） */
export type ScoreSnapshot = {
	sid: string,
	qid?: string | null,
	tier?: string,
	result?: string,
	base: number | null,
	ratio: number | null,
	points: number | null,
	source?: string,
};

/**
 *  计分相关设置（只取算分要用的几项）
 * 
 *  **字段名是驼峰**：前端传的是 JS 的 settings 对象（`halfRatio` / `fastBonus` /
 *  `wrongPenalty` / `buzzRankBonuses`）。少了 rename_all 会让这些值被 serde 静默忽略——
 *  这类"静默错值"在迁移里抓到过好几次了。
 */
export type ScoringSettings = {
	halfRatio?: number | null,
	fastBonus?: number | null,
	wrongPenalty?: number | null,
	/**
	 *  抢答名次加分（学习通"不同名次的分数"经验）：第 1 个抢答的队 +bonuses[0]，
	 *  第 2 个 +bonuses[1]，以此类推，名单之外的名次不加分。
	 *  传了名次就用名次分，不再叠加扁平 fastBonus；不传名次时 fastBonus 照旧（老行为）。
	 */
	buzzRankBonuses?: (number | null)[],
};

/**  课堂设置（`state.settings` 全集） */
export type Settings = {
	courseName: string,
	/**  部分正确计分系数 */
	halfRatio: number | null,
	/**  答错扣分（正数表示扣多少分） */
	wrongPenalty: number | null,
	/**  抢答额外加分（仅"答对"时生效） */
	fastBonus: number | null,
	/**  正确率低于该值 → 薄弱 */
	weakThreshold: number | null,
	/**  正确率高于该值 → 优势 */
	strongThreshold: number | null,
	/**  判定薄弱/优势所需最少作答次数 */
	minSample: number,
};

/**
 *  学生（持久化实体）
 * 
 *  `called` 是"被点名次数"，与 `rollcall::Student` 的对应字段一致；
 *  之所以这里也要带上，是因为教师端名单页会直接读它。
 */
export type Student = {
	id: string,
	name: string,
	teamId: string | null,
	active: boolean,
	joinedAt: number,
	called: number,
};

/**  学生命令（对应 cmd.kind = hello | buzz | answer） */
export type StudentCmd = {
	kind: string,
	teamId?: string | null,
	sid?: string | null,
	qid?: string | null,
	choice?: string[],
	text?: string | null,
	skip?: boolean,
	backlog?: boolean,
};

export type Team = {
	id: string,
	name: string,
	icon: string,
	color: string,
	order: number,
};

export type TeamStat = {
	teamId: string,
	name: string,
	color: string,
	icon: string,
	correct: number,
	attempts: number,
	creditRate: number | null,
	score: number | null,
	memberCount: number,
};

/**  题型（权重是计分核心） */
export type Tier = {
	key: string,
	label: string,
	weight: number | null,
	color?: string,
	desc?: string,
};

/**  题型统计（finalizeBucket 之后的形态） */
export type TierStat = {
	key: string,
	label: string,
	color?: string,
	weight?: number | null,
	attempts: number,
	correct: number,
	/**  掌握度百分比（已按 halfRatio 折算，保留一位小数，与 JS 的 pct 一致） */
	credit_rate?: number | null,
	/**  正确率百分比 */
	correct_rate?: number | null,
};
