//! @generated by scripts/gen-protocol.mjs —— 请勿手改；改契约请编辑 packages/protocol/messages.js
//!
//! 这样 Rust 枢纽与 Node 枢纽引用的报文名来自同一份契约，
//! 并由 tests/protocol.test.js 校验本文件始终是最新的。

/// 协议版本（与 packages/protocol/messages.js 的 version 一致）
pub const PROTOCOL_VERSION: u32 = 3;

/// 全部报文类型
pub const ALL_TYPES: &[&str] = &[
    "ack",
    "cmd",
    "cmd-backlog",
    "dump",
    "error",
    "hello",
    "leaderboard",
    "presence",
    "request",
    "request-dump",
    "state",
    "welcome",
];

/// 客户端 → 枢纽
pub const CLIENT_TO_HUB: &[&str] = &[
    "cmd",
    "dump",
    "hello",
    "request",
    "request-dump",
    "state",
];

/// 枢纽 → 客户端
pub const HUB_TO_CLIENT: &[&str] = &[
    "ack",
    "cmd",
    "cmd-backlog",
    "dump",
    "error",
    "leaderboard",
    "presence",
    "state",
    "welcome",
];

/// cmd.kind 取值
pub const CMD_KINDS: &[&str] = &[
    "answer",
    "buzz",
    "hello",
];

/// 快照顶层字段
pub const SNAPSHOT_FIELDS: &[&str] = &[
    "courseName",
    "meta",
    "room",
    "students",
    "teams",
    "updatedAt",
];

/// meta 字段
pub const META_FIELDS: &[&str] = &[
    "accepting",
    "buzz",
    "feed",
    "pending",
    "question",
    "questionIndex",
    "quizName",
    "recent",
    "reveal",
    "tierWeights",
];

